using OpenQuant.Shared;
using FreeQuant.Data;
using FreeQuant.FinChart;
using FreeQuant.FIX;
using FreeQuant.Indicators;
using FreeQuant.Instruments;
using FreeQuant.Series;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Reflection;
using System.Windows.Forms;

namespace OpenQuant.Shared.Charting
{
	partial class ChartColorManagerForm
  {

		  private IContainer components;
    private Button btnOk;
    private Button btnCancel;
    private Button btnDelete;
    private Button btnNew;
    private ImageList imageList;
    private ImageList imageList1;
    private Chart chart;
    private GroupBox groupBox1;
    private ListView ltvTemplates;
    private GroupBox groupBox2;
    private ListView ltvColorProperties;
    private ColumnHeader columnHeader1;
    private ColorEditor colorEditor;
    private Button btnSetDefault;
    private Button button1;

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      this.components = (IContainer) new Container();
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (ChartColorManagerForm));
      this.btnOk = new Button();
      this.btnCancel = new Button();
      this.btnDelete = new Button();
      this.btnNew = new Button();
      this.imageList = new ImageList(this.components);
      this.imageList1 = new ImageList(this.components);
      this.groupBox1 = new GroupBox();
      this.ltvTemplates = new ListView();
      this.groupBox2 = new GroupBox();
      this.ltvColorProperties = new ListView();
      this.columnHeader1 = new ColumnHeader();
      this.colorEditor = new ColorEditor();
      this.chart = new Chart();
      this.btnSetDefault = new Button();
      this.button1 = new Button();
      this.CancelButton = (IButtonControl) this.btnCancel;
      this.groupBox1.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.SuspendLayout();
      this.btnOk.DialogResult = DialogResult.Cancel;
      this.btnOk.Location = new Point(378, 465);
      this.btnOk.Name = "btnOk";
      this.btnOk.Size = new Size(75, 23);
      this.btnOk.TabIndex = 5;
      this.btnOk.Text = "Ok";
      this.btnOk.UseVisualStyleBackColor = true;
      this.btnOk.Click += new EventHandler(this.btnOk_Click);
      this.btnCancel.DialogResult = DialogResult.Cancel;
      this.btnCancel.Location = new Point(378, 465);
      this.btnCancel.Name = "btnCancel";
      this.btnCancel.Size = new Size(0, 0);
      this.btnCancel.TabIndex = 55;
      this.btnCancel.Text = "Ok";
      this.btnCancel.UseVisualStyleBackColor = true;
      this.btnDelete.Location = new Point(76, 465);
      this.btnDelete.Name = "btnDelete";
      this.btnDelete.Size = new Size(62, 23);
      this.btnDelete.TabIndex = 7;
      this.btnDelete.Text = "Delete";
      this.btnDelete.UseVisualStyleBackColor = true;
      this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
      this.btnNew.Location = new Point(8, 465);
      this.btnNew.Name = "btnNew";
      this.btnNew.Size = new Size(62, 23);
      this.btnNew.TabIndex = 6;
      this.btnNew.Text = "New";
      this.btnNew.UseVisualStyleBackColor = true;
      this.btnNew.Click += new EventHandler(this.btnNew_Click);
      this.imageList.ImageStream = (ImageListStreamer) componentResourceManager.GetObject("imageList.ImageStream");
      this.imageList.TransparentColor = Color.Transparent;
      this.imageList.Images.SetKeyName(0, "Color.png");
      this.imageList1.ImageStream = (ImageListStreamer) componentResourceManager.GetObject("imageList1.ImageStream");
      this.imageList1.TransparentColor = Color.Transparent;
      this.imageList1.Images.SetKeyName(0, "VSObject_Field.png");
      this.groupBox1.Controls.Add((Control) this.ltvTemplates);
      this.groupBox1.Location = new Point(8, 9);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(220, 189);
      this.groupBox1.TabIndex = 14;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Templates";
      this.ltvTemplates.Dock = DockStyle.Fill;
      this.ltvTemplates.HideSelection = false;
      this.ltvTemplates.LargeImageList = this.imageList;
      this.ltvTemplates.Location = new Point(3, 16);
      this.ltvTemplates.MultiSelect = false;
      this.ltvTemplates.Name = "ltvTemplates";
      this.ltvTemplates.Size = new Size(214, 170);
      this.ltvTemplates.SmallImageList = this.imageList;
      this.ltvTemplates.TabIndex = 13;
      this.ltvTemplates.UseCompatibleStateImageBehavior = false;
      this.ltvTemplates.View = View.List;
      this.ltvTemplates.SelectedIndexChanged += new EventHandler(this.ltvTemplates_SelectedIndexChanged);
      this.groupBox2.Controls.Add((Control) this.ltvColorProperties);
      this.groupBox2.Controls.Add((Control) this.colorEditor);
      this.groupBox2.Location = new Point(231, 9);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(222, 189);
      this.groupBox2.TabIndex = 15;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Colors";
      this.ltvColorProperties.Columns.AddRange(new ColumnHeader[1]
      {
        this.columnHeader1
      });
      this.ltvColorProperties.HeaderStyle = ColumnHeaderStyle.None;
      this.ltvColorProperties.HideSelection = false;
      this.ltvColorProperties.LargeImageList = this.imageList1;
      this.ltvColorProperties.Location = new Point(6, 16);
      this.ltvColorProperties.MultiSelect = false;
      this.ltvColorProperties.Name = "ltvColorProperties";
      this.ltvColorProperties.Size = new Size(213, 140);
      this.ltvColorProperties.SmallImageList = this.imageList1;
      this.ltvColorProperties.TabIndex = 11;
      this.ltvColorProperties.UseCompatibleStateImageBehavior = false;
      this.ltvColorProperties.View = View.Details;
      this.ltvColorProperties.SelectedIndexChanged += new EventHandler(this.ltvColorProperties_SelectedIndexChanged);
      this.columnHeader1.Width = 174;
      this.colorEditor.DrawMode = DrawMode.OwnerDrawFixed;
      this.colorEditor.DropDownStyle = ComboBoxStyle.DropDownList;
      this.colorEditor.FormattingEnabled = true;
      this.colorEditor.Items.AddRange(new object[0]);
      this.colorEditor.Location = new Point(6, 165);
      this.colorEditor.Name = "colorEditor";
      this.colorEditor.Size = new Size(213, 21);
      this.colorEditor.TabIndex = 10;
      this.colorEditor.SelectedIndexChanged += new EventHandler(this.colorEditor_SelectedIndexChanged);
			this.chart.ActionType = ChartActionType.Cross;
			this.chart.AllowDrop = true;
			this.chart.AutoScroll = true;
			this.chart.BackColor = Color.MidnightBlue;
			this.chart.BarSeriesStyle = BSStyle.Candle;
			this.chart.BorderColor = Color.Gray;
			this.chart.BottomAxisGridColor = Color.LightGray;
			this.chart.BottomAxisLabelColor = Color.LightGray;
			this.chart.CandleDownColor = Color.Black;
			this.chart.CandleUpColor = Color.Lime;
			this.chart.CanvasColor = Color.MidnightBlue;
			this.chart.ChartBackColor = Color.MidnightBlue;
			this.chart.ContextMenuEnabled = true;
			this.chart.CrossColor = Color.DarkGray;
			this.chart.DateTipRectangleColor = Color.LightGray;
			this.chart.DateTipTextColor = Color.Black;
      this.chart.DefaultLineColor = Color.White;
			this.chart.DrawItems = false;
			this.chart.Font = new Font("Microsoft Sans Serif", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 204);
			this.chart.Location = new Point(8, 204);
			this.chart.MinNumberOfBars = 30;
			this.chart.Name = "chart";
			this.chart.RightAxisGridColor = Color.DimGray;
			this.chart.RightAxisMajorTicksColor = Color.LightGray;
			this.chart.RightAxisMinorTicksColor = Color.LightGray;
			this.chart.RightAxisTextColor = Color.LightGray;
			this.chart.ScaleStyle = PadScaleStyle.Arith;
			this.chart.SessionEnd = TimeSpan.Parse("00:00:00");
			this.chart.SessionGridColor = Color.Empty;
			this.chart.SessionGridEnabled = false;
			this.chart.SessionStart = TimeSpan.Parse("00:00:00");
			this.chart.Size = new Size(445, byte.MaxValue);
			this.chart.SmoothingMode = SmoothingMode.HighSpeed;
			this.chart.SplitterColor = Color.LightGray;
			this.chart.TabIndex = 11;
			this.chart.UpdateStyle = ChartUpdateStyle.Trailing;
			this.chart.ValTipRectangleColor = Color.LightGray;
			this.chart.ValTipTextColor = Color.Black;
			this.chart.VolumeColor = Color.SteelBlue;
			this.chart.VolumePadVisible = false;
      this.btnSetDefault.Location = new Point(144, 465);
      this.btnSetDefault.Name = "btnSetDefault";
      this.btnSetDefault.Size = new Size(113, 23);
      this.btnSetDefault.TabIndex = 16;
      this.btnSetDefault.Text = "Set as Default";
      this.btnSetDefault.UseVisualStyleBackColor = true;
      this.btnSetDefault.Click += new EventHandler(this.btnSetDefault_Click);
      this.button1.DialogResult = DialogResult.Cancel;
      this.button1.Location = new Point(297, 465);
      this.button1.Name = "button1";
      this.button1.Size = new Size(75, 23);
      this.button1.TabIndex = 17;
      this.button1.Text = "Ok";
      this.button1.UseVisualStyleBackColor = true;
      this.button1.Visible = false;
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(462, 492);
      this.Controls.Add((Control) this.button1);
      this.Controls.Add((Control) this.btnSetDefault);
      this.Controls.Add((Control) this.btnDelete);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.btnNew);
      this.Controls.Add((Control) this.groupBox1);
      this.Controls.Add((Control) this.btnOk);
      this.Controls.Add((Control) this.btnCancel);
      this.Controls.Add((Control) this.chart);
      this.FormBorderStyle = FormBorderStyle.FixedDialog;
      this.MaximizeBox = false;
      this.MinimizeBox = false;
      this.Name = "ChartColorManager";
      this.ShowInTaskbar = false;
      this.StartPosition = FormStartPosition.CenterParent;
      this.Text = "Chart Color Manager";
      this.groupBox1.ResumeLayout(false);
      this.groupBox2.ResumeLayout(false);
      this.ResumeLayout(false);
    }

  }
}
