namespace OpenQuant.Shared.Charting
{
    partial class ChartColorManagerForm
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.Button btnOk;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.ImageList imageList;
        private System.Windows.Forms.ImageList imageList1;
       
        private OpenQuant.Shared.Charting.Chart chart;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.ListView ltvTemplates;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.ListView ltvColorProperties;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private OpenQuant.Shared.Charting.ColorEditor colorEditor;
        private System.Windows.Forms.Button btnSetDefault;
        private System.Windows.Forms.Button button1;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager componentResourceManager = new System.ComponentModel.ComponentResourceManager(typeof(ChartColorManagerForm));
            this.btnOk = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.btnDelete = new System.Windows.Forms.Button();
            this.btnNew = new System.Windows.Forms.Button();
            this.imageList = new System.Windows.Forms.ImageList(this.components);
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.ltvTemplates = new System.Windows.Forms.ListView();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.ltvColorProperties = new System.Windows.Forms.ListView();
            this.columnHeader1 = new System.Windows.Forms.ColumnHeader();
            this.colorEditor = new OpenQuant.Shared.Charting.ColorEditor();
            this.chart = new OpenQuant.Shared.Charting.Chart();
            this.btnSetDefault = new System.Windows.Forms.Button();
            this.button1 = new System.Windows.Forms.Button();
            this.CancelButton = this.btnCancel;
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            this.btnOk.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnOk.Location = new System.Drawing.Point(378, 465);
            this.btnOk.Name = "btnOk";
            this.btnOk.Size = new System.Drawing.Size(75, 23);
            this.btnOk.TabIndex = 5;
            this.btnOk.Text = "Ok";
            this.btnOk.UseVisualStyleBackColor = true;
            this.btnOk.Click += new System.EventHandler(this.btnOk_Click);
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.Location = new System.Drawing.Point(378, 465);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(0, 0);
            this.btnCancel.TabIndex = 55;
            this.btnCancel.Text = "Ok";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnDelete.Location = new System.Drawing.Point(76, 465);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(62, 23);
            this.btnDelete.TabIndex = 7;
            this.btnDelete.Text = "Delete";
            this.btnDelete.UseVisualStyleBackColor = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            this.btnNew.Location = new System.Drawing.Point(8, 465);
            this.btnNew.Name = "btnNew";
            this.btnNew.Size = new System.Drawing.Size(62, 23);
            this.btnNew.TabIndex = 6;
            this.btnNew.Text = "New";
            this.btnNew.UseVisualStyleBackColor = true;
            this.btnNew.Click += new System.EventHandler(this.btnNew_Click);
            //    this.imageList.ImageStream = (ImageListStreamer)componentResourceManager.GetObject("imageList.ImageStream");
            this.imageList.TransparentColor = System.Drawing.Color.Transparent;
            //  this.imageList.Images.SetKeyName(0, "Color.png");
            //    this.imageList1.ImageStream = (ImageListStreamer)componentResourceManager.GetObject("imageList1.ImageStream");
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            //   this.imageList1.Images.SetKeyName(0, "VSObject_Field.png");
            this.groupBox1.Controls.Add(this.ltvTemplates);
            this.groupBox1.Location = new System.Drawing.Point(8, 9);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(220, 189);
            this.groupBox1.TabIndex = 14;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Templates";
            this.ltvTemplates.Dock = System.Windows.Forms.DockStyle.Fill;
            this.ltvTemplates.HideSelection = false;
            this.ltvTemplates.LargeImageList = this.imageList;
            this.ltvTemplates.Location = new System.Drawing.Point(3, 16);
            this.ltvTemplates.MultiSelect = false;
            this.ltvTemplates.Name = "ltvTemplates";
            this.ltvTemplates.Size = new System.Drawing.Size(214, 170);
            this.ltvTemplates.SmallImageList = this.imageList;
            this.ltvTemplates.TabIndex = 13;
            this.ltvTemplates.UseCompatibleStateImageBehavior = false;
            this.ltvTemplates.View = System.Windows.Forms.View.List;
            this.ltvTemplates.SelectedIndexChanged += new System.EventHandler(this.ltvTemplates_SelectedIndexChanged);
            this.groupBox2.Controls.Add(this.ltvColorProperties);
            this.groupBox2.Controls.Add(this.colorEditor);
            this.groupBox2.Location = new System.Drawing.Point(231, 9);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(222, 189);
            this.groupBox2.TabIndex = 15;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Colors";
            this.ltvColorProperties.Columns.AddRange(new System.Windows.Forms.ColumnHeader[1]
            {
                this.columnHeader1
            });
            this.ltvColorProperties.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.None;
            this.ltvColorProperties.HideSelection = false;
            this.ltvColorProperties.LargeImageList = this.imageList1;
            this.ltvColorProperties.Location = new System.Drawing.Point(6, 16);
            this.ltvColorProperties.MultiSelect = false;
            this.ltvColorProperties.Name = "ltvColorProperties";
            this.ltvColorProperties.Size = new System.Drawing.Size(213, 140);
            this.ltvColorProperties.SmallImageList = this.imageList1;
            this.ltvColorProperties.TabIndex = 11;
            this.ltvColorProperties.UseCompatibleStateImageBehavior = false;
            this.ltvColorProperties.View = System.Windows.Forms.View.Details;
            this.ltvColorProperties.SelectedIndexChanged += new System.EventHandler(this.ltvColorProperties_SelectedIndexChanged);
            this.columnHeader1.Width = 174;
            this.colorEditor.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.colorEditor.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.colorEditor.FormattingEnabled = true;
            this.colorEditor.Items.AddRange(new object[0]);
            this.colorEditor.Location = new System.Drawing.Point(6, 165);
            this.colorEditor.Name = "colorEditor";
            this.colorEditor.Size = new System.Drawing.Size(213, 21);
            this.colorEditor.TabIndex = 10;
            this.colorEditor.SelectedIndexChanged += new System.EventHandler(this.colorEditor_SelectedIndexChanged);
            this.chart.ActionType = FreeQuant.FinChart.ChartActionType.Cross;
            this.chart.AllowDrop = true;
            this.chart.AutoScroll = true;
            this.chart.BackColor = System.Drawing.Color.MidnightBlue;
            this.chart.BarSeriesStyle = FreeQuant.FinChart.BSStyle.Candle;
            this.chart.BorderColor = System.Drawing.Color.Gray;
            this.chart.BottomAxisGridColor = System.Drawing.Color.LightGray;
            this.chart.BottomAxisLabelColor = System.Drawing.Color.LightGray;
            this.chart.CandleDownColor = System.Drawing.Color.Black;
            this.chart.CandleUpColor = System.Drawing.Color.Lime;
            this.chart.CanvasColor = System.Drawing.Color.MidnightBlue;
            this.chart.ChartBackColor = System.Drawing.Color.MidnightBlue;
            this.chart.ContextMenuEnabled = true;
            this.chart.CrossColor = System.Drawing.Color.DarkGray;
            this.chart.DateTipRectangleColor = System.Drawing.Color.LightGray;
            this.chart.DateTipTextColor = System.Drawing.Color.Black;
            this.chart.DefaultLineColor = System.Drawing.Color.White;
            this.chart.DrawItems = false;
            this.chart.Font = new System.Drawing.Font("Microsoft Sans Serif", 7f, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (byte)204);
            this.chart.Location = new System.Drawing.Point(8, 204);
            this.chart.MinNumberOfBars = 30;
            this.chart.Name = "chart";
            this.chart.RightAxisGridColor = System.Drawing.Color.DimGray;
            this.chart.RightAxisMajorTicksColor = System.Drawing.Color.LightGray;
            this.chart.RightAxisMinorTicksColor = System.Drawing.Color.LightGray;
            this.chart.RightAxisTextColor = System.Drawing.Color.LightGray;
            this.chart.ScaleStyle = FreeQuant.FinChart.PadScaleStyle.Arith;
            this.chart.SessionEnd = System.TimeSpan.Parse("00:00:00");
            this.chart.SessionGridColor = System.Drawing.Color.Empty;
            this.chart.SessionGridEnabled = false;
            this.chart.SessionStart = System.TimeSpan.Parse("00:00:00");
            this.chart.Size = new System.Drawing.Size(445, byte.MaxValue);
            this.chart.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighSpeed;
            this.chart.SplitterColor = System.Drawing.Color.LightGray;
            this.chart.TabIndex = 11;
            this.chart.UpdateStyle = FreeQuant.FinChart.ChartUpdateStyle.Trailing;
            this.chart.ValTipRectangleColor = System.Drawing.Color.LightGray;
            this.chart.ValTipTextColor = System.Drawing.Color.Black;
            this.chart.VolumeColor = System.Drawing.Color.SteelBlue;
            this.chart.VolumePadVisible = false;
            this.btnSetDefault.Location = new System.Drawing.Point(144, 465);
            this.btnSetDefault.Name = "btnSetDefault";
            this.btnSetDefault.Size = new System.Drawing.Size(113, 23);
            this.btnSetDefault.TabIndex = 16;
            this.btnSetDefault.Text = "Set as Default";
            this.btnSetDefault.UseVisualStyleBackColor = true;
            this.btnSetDefault.Click += new System.EventHandler(this.btnSetDefault_Click);
            this.button1.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.button1.Location = new System.Drawing.Point(297, 465);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 17;
            this.button1.Text = "Ok";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6f, 13f);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(462, 492);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.btnSetDefault);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.btnNew);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.btnOk);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.chart);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ChartColorManager";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Chart Color Manager";
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
